### ISSUE TITLE
a small problem in train_speaker.py

### ISSUE THREAD

**Issue by forwiat** [cvqluu/dropclass_speaker#1]
hello cvqluu, I see you using "ds_adapt" like a "global variable" in train function in train_speaker.py instead of function parameter.  So, I guess your orginal intention using "ds_adapt" (test dataset) is by function parameter?

**Comment by cvqluu** [comment]
Hi, yeah it should be a function variable.

`args` should also be a function variable so this is bad practice on my end.

Running `train_speaker.py` should still work, but I'll fix this up anyhow.

**Comment by cvqluu** [comment]
Changed in 4f3f762
